In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import pyplot
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [33]:
PATH = './Standard.csv'

In [34]:
Standard = clean(PATH)

In [35]:
PATH = './Shooting.csv'

In [36]:
Shooting = clean(PATH)

In [16]:
PATH = './Passing.csv'

In [25]:
Passing

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Total,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Cmp,Att,...,Cmp%,Ast,xA,A-xA,KP,01-Mar,PPA,CrsPA,Prog,Matches
1,1,Patrick van Aanholt,nl NED,DF,Crystal Palace,30-130,1990,9.2,453,560,...,51.4,1,0.7,0.3,9,35,19,4,62,Matches
2,2,Tammy Abraham,eng ENG,FW,Chelsea,23-096,1997,8.7,119,179,...,60,1,0.9,0.1,8,10,0,0,8,Matches
3,3,Che Adams,eng ENG,FW,Southampton,24-177,1996,15,229,330,...,70,4,3.9,0.1,18,17,10,0,31,Matches
4,4,Tosin Adarabioyo,eng ENG,DF,Fulham,23-104,1997,11,401,465,...,74.6,0,0.1,-0.1,3,27,1,0,17,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,459,Andre-Frank Zambo Anguissa,cm CMR,MF,Fulham,25-051,1995,13.3,597,698,...,64.3,2,1.2,0.8,14,77,11,4,55,Matches
460,460,Andi Zeqiri,ch SUI,"FW,DF",Brighton,21-198,1999,0.7,5,11,...,100,0,0,0,0,1,1,1,1,Matches
461,461,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24-022,1996,1.1,65,73,...,71.4,0,0,0,0,1,1,0,7,Matches
462,462,Hakim Ziyech,ma MAR,FW,Chelsea,27-293,1993,5,222,298,...,46.8,3,2.1,0.9,13,19,14,4,31,Matches
463,463,Kurt Zouma,fr FRA,DF,Chelsea,26-071,1994,15,1005,1111,...,80.9,0,0,0,1,72,2,0,46,Matches

In [ ]:
PATH = './Passing.csv'

In [26]:
Passing = clean(PATH)

In [27]:
Passing

,Player,Nation,Pos,Squad,Age,Born,90s,Cmp,Att,Cmp%,...,Cmp%,Ast,xA,A-xA,KP,01-Mar,PPA,CrsPA,Prog,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt,nl NED,DF,Crystal Palace,30-130,1990,9.2,453,560,80.9,...,51.4,1,0.7,0.3,9,35,19,4,62,Matches
2,Tammy Abraham,eng ENG,FW,Chelsea,23-096,1997,8.7,119,179,66.5,...,60,1,0.9,0.1,8,10,0,0,8,Matches
3,Che Adams,eng ENG,FW,Southampton,24-177,1996,15,229,330,69.4,...,70,4,3.9,0.1,18,17,10,0,31,Matches
4,Tosin Adarabioyo,eng ENG,DF,Fulham,23-104,1997,11,401,465,86.2,...,74.6,0,0.1,-0.1,3,27,1,0,17,Matches
5,Adrián,es ESP,GK,Liverpool,34-003,1987,2,43,62,69.4,...,37.9,0,0,0,0,0,0,0,0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Andre-Frank Zambo Anguissa,cm CMR,MF,Fulham,25-051,1995,13.3,597,698,85.5,...,64.3,2,1.2,0.8,14,77,11,4,55,Matches
460,Andi Zeqiri,ch SUI,"FW,DF",Brighton,21-198,1999,0.7,5,11,45.5,...,100,0,0,0,0,1,1,1,1,Matches
461,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24-022,1996,1.1,65,73,89,...,71.4,0,0,0,0,1,1,0,7,Matches
462,Hakim Ziyech,ma MAR,FW,Chelsea,27-293,1993,5,222,298,74.5,...,46.8,3,2.1,0.9,13,19,14,4,31,Matches
463,Kurt Zouma,fr FRA,DF,Chelsea,26-071,1994,15,1005,1111,90.5,...,80.9,0,0,0,1,72,2,0,46,Matches

In [31]:
PATH = './PassTypes.csv'

In [32]:
PassType = clean(PATH)

In [37]:
PATH = './GCA.csv'

In [38]:
GCA = clean(PATH)

In [39]:
PATH = './Defending.csv'

In [40]:
Defending = clean(PATH)

In [41]:
PATH = 'Possession.csv'

In [42]:
Possession = clean(PATH)