In [54]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import pyplot
%matplotlib inline
from sklearn.linear_model import LinearRegression
def clean(s):
    a=pd.read_csv(s,encoding='latin-1')
    a.columns=a.iloc[0]
    a=a.drop(0,axis=0)
    a=a.set_index('Rk')
    cols=pd.Series(a.columns)
    for dup in cols[cols.duplicated()].unique(): 
        cols[cols[cols == dup].index.values.tolist()] = [dup + '.' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]
  
    a.columns=cols
    return a

In [55]:
PATH = './Standard.csv'

In [56]:
Standard = clean(PATH)

In [57]:
PATH = './Shooting.csv'

In [58]:
Shooting = clean(PATH)

In [59]:
PATH = './Passing.csv'

In [60]:
PATH = './Passing.csv'

In [61]:
Passing = clean(PATH)

In [62]:
Passing

,Player,Nation,Pos,Squad,Age,Born,90s,Cmp,Att,Cmp%,...,Cmp%.3,Ast,xA,A-xA,KP,01-Mar,PPA,CrsPA,Prog,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt,nl NED,DF,Crystal Palace,30-130,1990,9.2,453,560,80.9,...,51.4,1,0.7,0.3,9,35,19,4,62,Matches
2,Tammy Abraham,eng ENG,FW,Chelsea,23-096,1997,8.7,119,179,66.5,...,60,1,0.9,0.1,8,10,0,0,8,Matches
3,Che Adams,eng ENG,FW,Southampton,24-177,1996,15,229,330,69.4,...,70,4,3.9,0.1,18,17,10,0,31,Matches
4,Tosin Adarabioyo,eng ENG,DF,Fulham,23-104,1997,11,401,465,86.2,...,74.6,0,0.1,-0.1,3,27,1,0,17,Matches
5,Adri√°n,es ESP,GK,Liverpool,34-003,1987,2,43,62,69.4,...,37.9,0,0,0,0,0,0,0,0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Andre-Frank Zambo Anguissa,cm CMR,MF,Fulham,25-051,1995,13.3,597,698,85.5,...,64.3,2,1.2,0.8,14,77,11,4,55,Matches
460,Andi Zeqiri,ch SUI,"FW,DF",Brighton,21-198,1999,0.7,5,11,45.5,...,100,0,0,0,0,1,1,1,1,Matches
461,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24-022,1996,1.1,65,73,89,...,71.4,0,0,0,0,1,1,0,7,Matches
462,Hakim Ziyech,ma MAR,FW,Chelsea,27-293,1993,5,222,298,74.5,...,46.8,3,2.1,0.9,13,19,14,4,31,Matches
463,Kurt Zouma,fr FRA,DF,Chelsea,26-071,1994,15,1005,1111,90.5,...,80.9,0,0,0,1,72,2,0,46,Matches

In [63]:
PATH = './PassTypes.csv'

In [64]:
PassType = clean(PATH)

In [65]:
PATH = './GCA.csv'

In [66]:
GCA = clean(PATH)

In [67]:
PATH = './Defending.csv'

In [68]:
Defending = clean(PATH)

In [69]:
PATH = 'Possession.csv'

In [70]:
Possession = clean(PATH)

In [71]:
Standard

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt,nl NED,DF,Crystal Palace,30-130,1990,10,9,829,9.2,...,0.11,0.7,0.7,0.7,0.08,0.07,0.15,0.08,0.15,Matches
2,Tammy Abraham,eng ENG,FW,Chelsea,23-096,1997,14,8,782,8.7,...,0.81,5.1,5.1,0.9,0.58,0.1,0.68,0.58,0.68,Matches
3,Che Adams,eng ENG,FW,Southampton,24-177,1996,16,16,"1,346",15,...,0.53,3.6,3.6,3.9,0.24,0.26,0.5,0.24,0.5,Matches
4,Tosin Adarabioyo,eng ENG,DF,Fulham,23-104,1997,11,11,990,11,...,0,0.5,0.5,0.1,0.04,0.01,0.06,0.04,0.06,Matches
5,Adri√°n,es ESP,GK,Liverpool,34-003,1987,2,2,180,2,...,0,0,0,0,0,0,0,0,0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Andre-Frank Zambo Anguissa,cm CMR,MF,Fulham,25-051,1995,15,13,"1,194",13.3,...,0.15,1,1,1.2,0.07,0.09,0.16,0.07,0.16,Matches
460,Andi Zeqiri,ch SUI,"FW,DF",Brighton,21-198,1999,2,0,64,0.7,...,0,0.3,0.3,0,0.44,0,0.44,0.44,0.44,Matches
461,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24-022,1996,2,1,103,1.1,...,0,0.2,0.2,0,0.14,0,0.14,0.14,0.14,Matches
462,Hakim Ziyech,ma MAR,FW,Chelsea,27-293,1993,8,6,451,5,...,0.8,0.5,0.5,2.1,0.09,0.41,0.5,0.09,0.5,Matches
463,Kurt Zouma,fr FRA,DF,Chelsea,26-071,1994,15,15,"1,350",15,...,0.27,0.9,0.9,0,0.06,0,0.07,0.06,0.07,Matches

1. Standard
2. Shooting
3. Passing
4. PassTypes
5. GCA
6. Defending
7. Posession

In [72]:
dfs=[]

In [73]:
dfs.append(Standard)
dfs.append(Shooting)
dfs.append(Passing)
dfs.append(PassType)
dfs.append(GCA)
dfs.append(Defending)
dfs.append(Possession)

In [74]:
result=pd.concat(dfs,axis=1)
result_cleaned=pd.concat(dfs,axis=1,join='inner')

In [75]:
len(list(result.columns))

202

In [76]:
len(list(result_cleaned))

202

In [77]:
result_cleaned= result.loc[:,~result.columns.duplicated()]

In [78]:
print(list(result_cleaned.columns))

['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A', 'G-PK', 'G+A-PK', 'xG', 'npxG', 'xA', 'xG.1', 'xA.1', 'xG+xA', 'npxG.1', 'npxG+xA', 'Matches', 'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'Dist', 'FK', 'npxG/Sh', 'G-xG', 'np:G-xG', 'Cmp', 'Att', 'Cmp%', 'TotDist', 'PrgDist', 'Cmp.1', 'Att.1', 'Cmp%.1', 'Cmp.2', 'Att.2', 'Cmp%.2', 'Cmp.3', 'Att.3', 'Cmp%.3', 'A-xA', 'KP', '01-Mar', 'PPA', 'CrsPA', 'Prog', 'Live', 'Dead', 'TB', 'Press', 'Sw', 'Crs', 'CK', 'In', 'Out', 'Str', 'Ground', 'Low', 'High', 'Left', 'Right', 'Head', 'TI', 'Other', 'Off', 'Out.1', 'Int', 'Blocks', 'SCA', 'SCA90', 'PassLive', 'PassDead', 'Drib', 'Fld', 'Def', 'GCA', 'GCA90', 'PassLive.1', 'PassDead.1', 'Drib.1', 'Sh.1', 'Fld.1', 'Def.1', 'OG', 'Tkl', 'TklW', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl.1', 'Tkl%', 'Past', 'Succ', '%', 'Def 3rd.1', 'Mid 3rd.1', 'Att 3rd.1', 'ShSv', 'Pass', 'Tkl+Int', 'Clr', 'Err', 'Touches', 'Def Pen', 'Att Pen', 'Succ%', '#Pl', 'Megs', 'Carries', 'Targ', 'Rec', 'Rec%', 'Miscon', 'Dispos']

In [79]:
result_cleaned['xG']

Rk
1      0.7
2      5.1
3      3.6
4      0.5
5        0
      ...
459      1
460    0.3
461    0.2
462    0.5
463    0.9
Name: xG, Length: 463, dtype: object

In [80]:
~Standard.columns.duplicated()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [81]:
Standard.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls.1',
       'Ast.1', 'G+A', 'G-PK', 'G+A-PK', 'xG', 'npxG', 'xA', 'xG.1', 'xA.1',
       'xG+xA', 'npxG.1', 'npxG+xA', 'Matches'],
      dtype='object', name=0)

In [82]:
Standard

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt,nl NED,DF,Crystal Palace,30-130,1990,10,9,829,9.2,...,0.11,0.7,0.7,0.7,0.08,0.07,0.15,0.08,0.15,Matches
2,Tammy Abraham,eng ENG,FW,Chelsea,23-096,1997,14,8,782,8.7,...,0.81,5.1,5.1,0.9,0.58,0.1,0.68,0.58,0.68,Matches
3,Che Adams,eng ENG,FW,Southampton,24-177,1996,16,16,"1,346",15,...,0.53,3.6,3.6,3.9,0.24,0.26,0.5,0.24,0.5,Matches
4,Tosin Adarabioyo,eng ENG,DF,Fulham,23-104,1997,11,11,990,11,...,0,0.5,0.5,0.1,0.04,0.01,0.06,0.04,0.06,Matches
5,Adri√°n,es ESP,GK,Liverpool,34-003,1987,2,2,180,2,...,0,0,0,0,0,0,0,0,0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Andre-Frank Zambo Anguissa,cm CMR,MF,Fulham,25-051,1995,15,13,"1,194",13.3,...,0.15,1,1,1.2,0.07,0.09,0.16,0.07,0.16,Matches
460,Andi Zeqiri,ch SUI,"FW,DF",Brighton,21-198,1999,2,0,64,0.7,...,0,0.3,0.3,0,0.44,0,0.44,0.44,0.44,Matches
461,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24-022,1996,2,1,103,1.1,...,0,0.2,0.2,0,0.14,0,0.14,0.14,0.14,Matches
462,Hakim Ziyech,ma MAR,FW,Chelsea,27-293,1993,8,6,451,5,...,0.8,0.5,0.5,2.1,0.09,0.41,0.5,0.09,0.5,Matches
463,Kurt Zouma,fr FRA,DF,Chelsea,26-071,1994,15,15,"1,350",15,...,0.27,0.9,0.9,0,0.06,0,0.07,0.06,0.07,Matches

In [52]:
Standard.rename({"xG":"xG/90"}, axis='columns')

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG/90,npxG,xA,xG/90,xA,xG+xA,npxG,npxG+xA,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt,nl NED,DF,Crystal Palace,30-130,1990,10,9,829,9.2,...,0.11,0.7,0.7,0.7,0.08,0.07,0.15,0.08,0.15,Matches
2,Tammy Abraham,eng ENG,FW,Chelsea,23-096,1997,14,8,782,8.7,...,0.81,5.1,5.1,0.9,0.58,0.1,0.68,0.58,0.68,Matches
3,Che Adams,eng ENG,FW,Southampton,24-177,1996,16,16,"1,346",15,...,0.53,3.6,3.6,3.9,0.24,0.26,0.5,0.24,0.5,Matches
4,Tosin Adarabioyo,eng ENG,DF,Fulham,23-104,1997,11,11,990,11,...,0,0.5,0.5,0.1,0.04,0.01,0.06,0.04,0.06,Matches
5,Adri√°n,es ESP,GK,Liverpool,34-003,1987,2,2,180,2,...,0,0,0,0,0,0,0,0,0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Andre-Frank Zambo Anguissa,cm CMR,MF,Fulham,25-051,1995,15,13,"1,194",13.3,...,0.15,1,1,1.2,0.07,0.09,0.16,0.07,0.16,Matches
460,Andi Zeqiri,ch SUI,"FW,DF",Brighton,21-198,1999,2,0,64,0.7,...,0,0.3,0.3,0,0.44,0,0.44,0.44,0.44,Matches
461,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24-022,1996,2,1,103,1.1,...,0,0.2,0.2,0,0.14,0,0.14,0.14,0.14,Matches
462,Hakim Ziyech,ma MAR,FW,Chelsea,27-293,1993,8,6,451,5,...,0.8,0.5,0.5,2.1,0.09,0.41,0.5,0.09,0.5,Matches
463,Kurt Zouma,fr FRA,DF,Chelsea,26-071,1994,15,15,"1,350",15,...,0.27,0.9,0.9,0,0.06,0,0.07,0.06,0.07,Matches

In [53]:
cols=pd.Series(Standard.columns)
for dup in cols[cols.duplicated()].unique(): 
    cols[cols[cols == dup].index.values.tolist()] = [dup + '.' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]
    
# rename the columns with the cols list.
Standard.columns=cols
Standard

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt,nl NED,DF,Crystal Palace,30-130,1990,10,9,829,9.2,...,0.11,0.7,0.7,0.7,0.08,0.07,0.15,0.08,0.15,Matches
2,Tammy Abraham,eng ENG,FW,Chelsea,23-096,1997,14,8,782,8.7,...,0.81,5.1,5.1,0.9,0.58,0.1,0.68,0.58,0.68,Matches
3,Che Adams,eng ENG,FW,Southampton,24-177,1996,16,16,"1,346",15,...,0.53,3.6,3.6,3.9,0.24,0.26,0.5,0.24,0.5,Matches
4,Tosin Adarabioyo,eng ENG,DF,Fulham,23-104,1997,11,11,990,11,...,0,0.5,0.5,0.1,0.04,0.01,0.06,0.04,0.06,Matches
5,Adri√°n,es ESP,GK,Liverpool,34-003,1987,2,2,180,2,...,0,0,0,0,0,0,0,0,0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Andre-Frank Zambo Anguissa,cm CMR,MF,Fulham,25-051,1995,15,13,"1,194",13.3,...,0.15,1,1,1.2,0.07,0.09,0.16,0.07,0.16,Matches
460,Andi Zeqiri,ch SUI,"FW,DF",Brighton,21-198,1999,2,0,64,0.7,...,0,0.3,0.3,0,0.44,0,0.44,0.44,0.44,Matches
461,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24-022,1996,2,1,103,1.1,...,0,0.2,0.2,0,0.14,0,0.14,0.14,0.14,Matches
462,Hakim Ziyech,ma MAR,FW,Chelsea,27-293,1993,8,6,451,5,...,0.8,0.5,0.5,2.1,0.09,0.41,0.5,0.09,0.5,Matches
463,Kurt Zouma,fr FRA,DF,Chelsea,26-071,1994,15,15,"1,350",15,...,0.27,0.9,0.9,0,0.06,0,0.07,0.06,0.07,Matches

In [84]:
list(result_cleaned)

['Player',
 'Nation',
 'Pos',
 'Squad',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 '90s',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA',
 'Matches',
 'Sh',
 'SoT',
 'SoT%',
 'Sh/90',
 'SoT/90',
 'G/Sh',
 'G/SoT',
 'Dist',
 'FK',
 'npxG/Sh',
 'G-xG',
 'np:G-xG',
 'Cmp',
 'Att',
 'Cmp%',
 'TotDist',
 'PrgDist',
 'Cmp.1',
 'Att.1',
 'Cmp%.1',
 'Cmp.2',
 'Att.2',
 'Cmp%.2',
 'Cmp.3',
 'Att.3',
 'Cmp%.3',
 'A-xA',
 'KP',
 '01-Mar',
 'PPA',
 'CrsPA',
 'Prog',
 'Live',
 'Dead',
 'TB',
 'Press',
 'Sw',
 'Crs',
 'CK',
 'In',
 'Out',
 'Str',
 'Ground',
 'Low',
 'High',
 'Left',
 'Right',
 'Head',
 'TI',
 'Other',
 'Off',
 'Out.1',
 'Int',
 'Blocks',
 'SCA',
 'SCA90',
 'PassLive',
 'PassDead',
 'Drib',
 'Fld',
 'Def',
 'GCA',
 'GCA90',
 'PassLive.1',
 'PassDead.1',
 'Drib.1',
 'Sh.1',
 'Fld.1',
 'Def.1',
 'OG',
 'Tkl',
 'TklW',
 'Def 3rd',
 'Mid 3rd',
 'Att 3rd',
 'Tkl.1',
 'Tkl%',
 'Past',
 'Succ',
 '%',
 'Def 3rd.1',
 'Mid 3rd.1',
 'Att 3rd.1',
 'ShSv',
 'Pass',
 'Tkl+Int',
 'Clr',
 'Err',
 'Touches',
 'Def Pen',
 'Att Pen',
 'Succ%',
 '#Pl',
 'Megs',
 'Carries',
 'Targ',
 'Rec',
 'Rec%',
 'Miscon',
 'Dispos']

In [96]:
def merger(l):
    result=pd.concat(dfs,axis=1)
    cols=pd.Series(result.columns)
    for dup in cols[cols.duplicated()].unique(): 
        cols[cols[cols == dup].index.values.tolist()] = [dup + '.' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]
        
    result.columns=cols
    return result

In [122]:
semi=merger(dfs)

In [98]:
list(semi.columns)

['Player',
 'Nation',
 'Pos',
 'Squad',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 '90s',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA',
 'Matches',
 'Player.1',
 'Nation.1',
 'Pos.1',
 'Squad.1',
 'Age.1',
 'Born.1',
 '90s.1',
 'Gls.1',
 'Sh',
 'SoT',
 'SoT%',
 'Sh/90',
 'SoT/90',
 'G/Sh',
 'G/SoT',
 'Dist',
 'FK',
 'PK.1',
 'PKatt.1',
 'xG.1',
 'npxG.1',
 'npxG/Sh',
 'G-xG',
 'np:G-xG',
 'Matches.1',
 'Player.2',
 'Nation.2',
 'Pos.2',
 'Squad.2',
 'Age.2',
 'Born.2',
 '90s.2',
 'Cmp',
 'Att',
 'Cmp%',
 'TotDist',
 'PrgDist',
 'Cmp.1',
 'Att.1',
 'Cmp%.1',
 'Cmp.2',
 'Att.2',
 'Cmp%.2',
 'Cmp.3',
 'Att.3',
 'Cmp%.3',
 'Ast.1',
 'xA.1',
 'A-xA',
 'KP',
 '01-Mar',
 'PPA',
 'CrsPA',
 'Prog',
 'Matches.2',
 'Player.3',
 'Nation.3',
 'Pos.3',
 'Squad.3',
 'Age.3',
 'Born.3',
 '90s.3',
 'Att.1',
 'Live',
 'Dead',
 'FK.1',
 'TB',
 'Press',
 'Sw',
 'Crs',
 'CK',
 'In',
 'Out',
 'Str',
 'Ground',
 'Low',
 'High',
 'Left',
 'Right',
 'Head',
 'TI',
 'Other',
 'Cmp.1',
 'Off',
 'Out.1',
 'Int',
 'Blocks',
 'Matches.3',
 'Player.4',
 'Nation.4',
 'Pos.4',
 'Squad.4',
 'Age.4',
 'Born.4',
 '90s.4',
 'SCA',
 'SCA90',
 'PassLive',
 'PassDead',
 'Drib',
 'Sh.1',
 'Fld',
 'Def',
 'GCA',
 'GCA90',
 'PassLive.1',
 'PassDead.1',
 'Drib.1',
 'Sh.1',
 'Fld.1',
 'Def.1',
 'OG',
 'Matches.4',
 'Player.5',
 'Nation.5',
 'Pos.5',
 'Squad.5',
 'Age.5',
 'Born.5',
 '90s.5',
 'Tkl',
 'TklW',
 'Def 3rd',
 'Mid 3rd',
 'Att 3rd',
 'Tkl.1',
 'Att.2',
 'Tkl%',
 'Past',
 'Press.1',
 'Succ',
 '%',
 'Def 3rd.1',
 'Mid 3rd.1',
 'Att 3rd.1',
 'Blocks.1',
 'Sh.2',
 'ShSv',
 'Pass',
 'Int.1',
 'Tkl+Int',
 'Clr',
 'Err',
 'Matches.5',
 'Player.6',
 'Nation.6',
 'Pos.6',
 'Squad.6',
 'Age.6',
 'Born.6',
 '90s.6',
 'Touches',
 'Def Pen',
 'Def 3rd.1',
 'Mid 3rd.1',
 'Att 3rd.1',
 'Att Pen',
 'Live.1',
 'Succ.1',
 'Att.3',
 'Succ%',
 '#Pl',
 'Megs',
 'Carries',
 'TotDist.1',
 'PrgDist.1',
 'Targ',
 'Rec',
 'Rec%',
 'Miscon',
 'Dispos',
 'Matches.6']

In [117]:
fina={'Pos':'Pos', 'Min':'Min', 'Gls':'Gls',
       'Ast':"Ast", 'PK':'PK', 'Shots':'Sh', 'SoT':'SoT', 'Touches':'Touches', 'xG':'xG', 'npxG':'npxG', 'xA':'xA', 'SCA':'SCA',
       'GCA':'GCA', 'PassCmp':'Cmp', 'PassAtt':'Att', 'PassCmp%':'Cmp%', 'Through':'TB', 'PressPass':'Press',
       'Switches':'Sw', 'Crosses':'Crs', 'KP':'KP', 'Final ThirdPasses':'01-Mar', 'ProgressivePasses':'Prog',
       'PassPrgDist':'PrgDist', 'Carries':'Carries', 'TotDist':'TotDist','PrgDist':'PrgDist.1',  'Succ':'Succ.1', 'Att':'Att', 'Tkl':'Tkl',
       'TklW':'TklW','Press':'Press.1',  'PressSucc':'Succ', 'Press%':'%', 'Int':'Int', 'Tkl+Int':'Tkl+Int', 'Blocks':'Blocks',
       'Clr':'Clr', 'Def Pen':'Def Pen', 'Def 3rd Touches':'Def 3rd', 'Targ':'Targ', 'Rec':'Rec', 'Rec%':'Rec%'}

In [118]:
fina

{'Pos': 'Pos',
 'Min': 'Min',
 'Gls': 'Gls',
 'Ast': 'Ast',
 'PK': 'PK',
 'Shots': 'Sh',
 'SoT': 'SoT',
 'Touches': 'Touches',
 'xG': 'xG',
 'npxG': 'npxG',
 'xA': 'xA',
 'SCA': 'SCA',
 'GCA': 'GCA',
 'PassCmp': 'Cmp',
 'PassAtt': 'Att',
 'PassCmp%': 'Cmp%',
 'Through': 'TB',
 'PressPass': 'Press',
 'Switches': 'Sw',
 'Crosses': 'Crs',
 'KP': 'KP',
 'Final ThirdPasses': '01-Mar',
 'ProgressivePasses': 'Prog',
 'PassPrgDist': 'PrgDist',
 'Carries': 'Carries',
 'TotDist': 'TotDist',
 'PrgDist': 'PrgDist.1',
 'Succ': 'Succ.1',
 'Att': 'Att',
 'Tkl': 'Tkl',
 'TklW': 'TklW',
 'Press': 'Press.1',
 'PressSucc': 'Succ',
 'Press%': '%',
 'Int': 'Int',
 'Tkl+Int': 'Tkl+Int',
 'Blocks': 'Blocks',
 'Clr': 'Clr',
 'Def Pen': 'Def Pen',
 'Def 3rd Touches': 'Def 3rd',
 'Targ': 'Targ',
 'Rec': 'Rec',
 'Rec%': 'Rec%'}

In [119]:
hehe=list(fina.values())
haha=list(fina.keys())

In [120]:
dici={}
for i in range(len(haha)):
    dici[hehe[i]]=haha[i]

In [121]:
dici

{'Pos': 'Pos',
 'Min': 'Min',
 'Gls': 'Gls',
 'Ast': 'Ast',
 'PK': 'PK',
 'Sh': 'Shots',
 'SoT': 'SoT',
 'Touches': 'Touches',
 'xG': 'xG',
 'npxG': 'npxG',
 'xA': 'xA',
 'SCA': 'SCA',
 'GCA': 'GCA',
 'Cmp': 'PassCmp',
 'Att': 'Att',
 'Cmp%': 'PassCmp%',
 'TB': 'Through',
 'Press': 'PressPass',
 'Sw': 'Switches',
 'Crs': 'Crosses',
 'KP': 'KP',
 '01-Mar': 'Final ThirdPasses',
 'Prog': 'ProgressivePasses',
 'PrgDist': 'PassPrgDist',
 'Carries': 'Carries',
 'TotDist': 'TotDist',
 'PrgDist.1': 'PrgDist',
 'Succ.1': 'Succ',
 'Tkl': 'Tkl',
 'TklW': 'TklW',
 'Press.1': 'Press',
 'Succ': 'PressSucc',
 '%': 'Press%',
 'Int': 'Int',
 'Tkl+Int': 'Tkl+Int',
 'Blocks': 'Blocks',
 'Clr': 'Clr',
 'Def Pen': 'Def Pen',
 'Def 3rd': 'Def 3rd Touches',
 'Targ': 'Targ',
 'Rec': 'Rec',
 'Rec%': 'Rec%'}

In [123]:
semi=semi.rename(dici)

In [124]:
semi=semi[hehe]

In [126]:
dici

{'Pos': 'Pos',
 'Min': 'Min',
 'Gls': 'Gls',
 'Ast': 'Ast',
 'PK': 'PK',
 'Sh': 'Shots',
 'SoT': 'SoT',
 'Touches': 'Touches',
 'xG': 'xG',
 'npxG': 'npxG',
 'xA': 'xA',
 'SCA': 'SCA',
 'GCA': 'GCA',
 'Cmp': 'PassCmp',
 'Att': 'Att',
 'Cmp%': 'PassCmp%',
 'TB': 'Through',
 'Press': 'PressPass',
 'Sw': 'Switches',
 'Crs': 'Crosses',
 'KP': 'KP',
 '01-Mar': 'Final ThirdPasses',
 'Prog': 'ProgressivePasses',
 'PrgDist': 'PassPrgDist',
 'Carries': 'Carries',
 'TotDist': 'TotDist',
 'PrgDist.1': 'PrgDist',
 'Succ.1': 'Succ',
 'Tkl': 'Tkl',
 'TklW': 'TklW',
 'Press.1': 'Press',
 'Succ': 'PressSucc',
 '%': 'Press%',
 'Int': 'Int',
 'Tkl+Int': 'Tkl+Int',
 'Blocks': 'Blocks',
 'Clr': 'Clr',
 'Def Pen': 'Def Pen',
 'Def 3rd': 'Def 3rd Touches',
 'Targ': 'Targ',
 'Rec': 'Rec',
 'Rec%': 'Rec%'}

In [125]:
semi

,Pos,Min,Gls,Ast,PK,Sh,SoT,Touches,xG,npxG,...,%,Int,Tkl+Int,Blocks,Clr,Def Pen,Def 3rd,Targ,Rec,Rec%
Rk,,,,,,,,,,,,,,,,,,,,,
1,DF,829,0,1,0,12,5,641,0.7,0.7,...,37,11,27,13,14,27,7,435,403,92.6
2,FW,782,6,1,0,27,11,278,5.1,5.1,...,23,3,7,11,11,15,1,365,201,55.1
3,FW,"1,346",4,4,0,28,14,499,3.6,3.6,...,33.7,9,20,17,11,12,4,775,388,50.1
4,DF,990,0,0,0,9,0,584,0.5,0.5,...,27.5,4,28,2,69,126,14,368,353,95.9
5,GK,180,0,0,0,0,0,69,0,0,...,0,0,0,0,0,64,0,28,27,96.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,MF,"1,194",0,2,0,15,1,888,1,1,...,26.2,13,82,11,12,23,13,678,598,88.2
460,"FW,DF",64,0,0,0,5,0,20,0.3,0.3,...,20,0,1,1,0,0,0,34,13,38.2
461,DF,103,0,0,0,1,1,82,0.2,0.2,...,50,0,2,2,2,4,0,63,60,95.2
462,FW,451,1,3,0,10,3,353,0.5,0.5,...,29.4,2,8,7,0,3,1,333,274,82.3
463,DF,"1,350",4,0,0,14,7,1259,0.9,0.9,...,37.9,7,26,4,84,180,6,963,946,98.2

## IMPORTANT

In [174]:
dfs=[]
dfs.append(Standard)
dfs.append(Shooting)
dfs.append(Passing)
dfs.append(PassType)
dfs.append(GCA)
dfs.append(Defending)
dfs.append(Possession)

In [175]:
def merger(l):
    # Takes as input  a list of dataframes
    # Returns a dataframe of cleaned required data
    result=pd.concat(dfs,axis=1)
    cols=pd.Series(result.columns)
    for dup in cols[cols.duplicated()].unique(): 
        cols[cols[cols == dup].index.values.tolist()] = [dup + '.' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]
        
    result.columns=cols
    fina={'Pos': 'Pos',
         'Min': 'Min',
         'Gls': 'Gls',
         'Ast': 'Ast',
         'PK': 'PK',
         'Sh': 'Shots',
         'SoT': 'SoT',
         'Touches': 'Touches',
         'xG': 'xG',
         'npxG': 'npxG',
         'xA': 'xA',
         'SCA': 'SCA',
         'GCA': 'GCA',
         'Cmp': 'PassCmp',
         'Att': 'Att',
         'Cmp%': 'PassCmp%',
         'TB': 'Through',
         'Press': 'PressPass',
         'Sw': 'Switches',
         'Crs': 'Crosses',
         'KP': 'KP',
         '01-Mar': 'Final ThirdPasses',
         'Prog': 'ProgressivePasses',
         'PrgDist': 'PassPrgDist',
         'Carries': 'Carries',
         'TotDist': 'TotDist',
         'PrgDist.1': 'PrgDist',
         'Succ.1': 'Succ',
         'Tkl': 'Tkl',
         'TklW': 'TklW',
         'Press.1': 'Press',
         'Succ': 'PressSucc',
         '%': 'Press%',
         'Int': 'Int',
         'Tkl+Int': 'Tkl+Int',
         'Blocks': 'Blocks',
         'Clr': 'Clr',
         'Def Pen': 'Def Pen',
         'Def 3rd': 'Def 3rd Touches',
         'Targ': 'Targ',
         'Rec': 'Rec',
         'Rec%': 'Rec%'}
    hehe=list(fina.keys())
    hi=['Player',
         'Nation',
         'Squad',
         'Age',
         'Born',
         'MP']
    hi.extend(hehe)
    result=result.rename(dici)
    result=result[hi]
    for i in range(463):
        temp=result.loc[str(i+1)]['Nation']
        temp=temp.split()
        result.at[str(i+1),'Nation']=temp[1]
    return result

In [176]:
nice=merger(dfs)

In [177]:
nice

,Player,Nation,Squad,Age,Born,MP,Pos,Min,Gls,Ast,...,%,Int,Tkl+Int,Blocks,Clr,Def Pen,Def 3rd,Targ,Rec,Rec%
Rk,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt,NED,Crystal Palace,30-130,1990,10,DF,829,0,1,...,37,11,27,13,14,27,7,435,403,92.6
2,Tammy Abraham,ENG,Chelsea,23-096,1997,14,FW,782,6,1,...,23,3,7,11,11,15,1,365,201,55.1
3,Che Adams,ENG,Southampton,24-177,1996,16,FW,"1,346",4,4,...,33.7,9,20,17,11,12,4,775,388,50.1
4,Tosin Adarabioyo,ENG,Fulham,23-104,1997,11,DF,990,0,0,...,27.5,4,28,2,69,126,14,368,353,95.9
5,Adri√°n,ESP,Liverpool,34-003,1987,2,GK,180,0,0,...,0,0,0,0,0,64,0,28,27,96.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Andre-Frank Zambo Anguissa,CMR,Fulham,25-051,1995,15,MF,"1,194",0,2,...,26.2,13,82,11,12,23,13,678,598,88.2
460,Andi Zeqiri,SUI,Brighton,21-198,1999,2,"FW,DF",64,0,0,...,20,0,1,1,0,0,0,34,13,38.2
461,Oleksandr Zinchenko,UKR,Manchester City,24-022,1996,2,DF,103,0,0,...,50,0,2,2,2,4,0,63,60,95.2
462,Hakim Ziyech,MAR,Chelsea,27-293,1993,8,FW,451,1,3,...,29.4,2,8,7,0,3,1,333,274,82.3
463,Kurt Zouma,FRA,Chelsea,26-071,1994,15,DF,"1,350",4,0,...,37.9,7,26,4,84,180,6,963,946,98.2